In [1]:
import numpy as np
import pandas as pd
import sklearn
from matplotlib import pyplot as plt
import warnings
warnings.filterwarnings('ignore')

# Stemming in NLP

In [2]:
from nltk.stem import PorterStemmer

In [3]:
ps = PorterStemmer()
ps

In [4]:
word = ['change', 'changes', 'changing', 'changed']
word

['change', 'changes', 'changing', 'changed']

In [5]:
for i in word :
    print(ps.stem(i))

chang
chang
chang
chang

In [6]:
ps.stem('mocking')

'mock'

## For example, when applying stemming to the sentence, "The fishers are fishing in the fished waters," a stemming algorithm strips the suffixes to yield:"The fisher are fish in the fish water"

In [7]:
sen = "The fishers are fishing in the fished waters" 
print('before stemming :', sen)

before stemming : The fishers are fishing in the fished waters

In [8]:
from nltk.tokenize import word_tokenize
wt = word_tokenize
wt

In [9]:
tokens = wt(sen)
tokens

['The', 'fishers', 'are', 'fishing', 'in', 'the', 'fished', 'waters']

In [10]:
res = ''
for i in tokens :
    res += ps.stem(i)
    res += ' '

print('after stemming :', res)

after stemming : the fisher are fish in the fish water

# Lemmatization in NLP

In [11]:
from nltk.stem import WordNetLemmatizer
wnl = WordNetLemmatizer()
wnl

In [12]:
sen

'The fishers are fishing in the fished waters'

In [13]:
tokens

['The', 'fishers', 'are', 'fishing', 'in', 'the', 'fished', 'waters']

## The final sentence after lemmatization is:"The fisher be fish in the fish water"

In [14]:
print('before lemmatization :', sen)

before lemmatization : The fishers are fishing in the fished waters

In [15]:
res1 = ''
for i in tokens :
    res1 += wnl.lemmatize(i, pos = 'v')
    res1 += ' '

print('after lemmatization :', res1)

after lemmatization : The fishers be fish in the fish water

In [16]:
"The fisher be fish in the fish water"

'The fisher be fish in the fish water'

In [17]:
print(ps.stem('wolves'))
print(wnl.lemmatize('wolves'))

wolv
wolf

In [18]:
word

['change', 'changes', 'changing', 'changed']

In [19]:
for i in word :
    print(wnl.lemmatize(i))

change
change
changing
changed

# Tokenization in NLP

In Python, there are several libraries and tools available for performing tokenization and other NLP tasks. Here are a few examples using popular libraries.

# NLTK

In [20]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [21]:
sen1 = "Machine Learning is fascinating"
word_tokens = word_tokenize(sen1)
word_tokens

['Machine', 'Learning', 'is', 'fascinating']

In [22]:
sen2 = "Artificial Intelligence is an emerging technology. Machine learning is fascinating. Computer Vision handles images."
sent_tokens = sent_tokenize(sen2)
sent_tokens

['Artificial Intelligence is an emerging technology.',
 'Machine learning is fascinating.',
 'Computer Vision handles images.']

# spaCy

spaCy is another powerful library for NLP. To install spaCy, you can run pip install spacy and then download the appropriate language model. Here's an example of tokenization using spaCy.

In [23]:
import spacy
spc = spacy.load("en_core_web_sm")
# import en_core_web_sm
# nlp = en_core_web_sm.load()

In [24]:
doc = spc(sen2)
word_token = [token.text for token in doc]
print(word_token)

['Artificial', 'Intelligence', 'is', 'an', 'emerging', 'technology', '.', 'Machine', 'learning', 'is', 'fascinating', '.', 'Computer', 'Vision', 'handles', 'images', '.']

In [25]:
text = spc(sen2)
sent_token = []
for i in text.sents :
    sent_token.append(i.text)

print(sent_token)

['Artificial Intelligence is an emerging technology.', 'Machine learning is fascinating.', 'Computer Vision handles images.']

In [26]:
import spacy
spc = spacy.load('en_core_web_sm')

doc = spc('I am Mohi Uddin Maruf. I am 25 years old. I live in Boalkhali.')
wtk = [i.text for i in doc]
print(wtk)

stk = [i.text for i in doc.sents]
print(stk)

['I', 'am', 'Mohi', 'Uddin', 'Maruf', '.', 'I', 'am', '25', 'years', 'old', '.', 'I', 'live', 'in', 'Boalkhali', '.']
['I am Mohi Uddin Maruf.', 'I am 25 years old.', 'I live in Boalkhali.']

# Transformers

Transformers is a library built by Hugging Face that provides state-of-the-art pre-trained models for NLP. It offers various functionalities, including tokenization. To install Transformers, run pip install transformers. Here's an example of tokenization using Transformers.

In [27]:
import os
from huggingface_hub import login

os.environ["HF_TOKEN"] = "your_actual_token_here"
# Alternatively, use: login(token="your_actual_token_here")

In [28]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
print(tokenizer.tokenize(sen2))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

['artificial', 'intelligence', 'is', 'an', 'emerging', 'technology', '.', 'machine', 'learning', 'is', 'fascinating', '.', 'computer', 'vision', 'handles', 'images', '.']

# Named Entity Tokenization using NLTK

To perform named entity tokenization using NLTK (Natural Language Toolkit), you can utilize the named entity recognition (NER) functionality provided by NLTK. Here's an example of how to extract named entity tokens from a sentence using NLTK

In [29]:
from nltk import word_tokenize, sent_tokenize, PunktSentenceTokenizer, pos_tag, ne_chunk

In [30]:
sen2

'Artificial Intelligence is an emerging technology. Machine learning is fascinating. Computer Vision handles images.'

## using PunktSentenceTokenizer

In [31]:
print(PunktSentenceTokenizer().tokenize(sen2))

['Artificial Intelligence is an emerging technology.', 'Machine learning is fascinating.', 'Computer Vision handles images.']

In [32]:
wtokens = word_tokenize(sen2)
print(wtokens)

['Artificial', 'Intelligence', 'is', 'an', 'emerging', 'technology', '.', 'Machine', 'learning', 'is', 'fascinating', '.', 'Computer', 'Vision', 'handles', 'images', '.']

In [33]:
pos_tags = pos_tag(wtokens)
print(pos_tags)

[('Artificial', 'JJ'), ('Intelligence', 'NNP'), ('is', 'VBZ'), ('an', 'DT'), ('emerging', 'VBG'), ('technology', 'NN'), ('.', '.'), ('Machine', 'NNP'), ('learning', 'NN'), ('is', 'VBZ'), ('fascinating', 'VBG'), ('.', '.'), ('Computer', 'NNP'), ('Vision', 'NNP'), ('handles', 'VBZ'), ('images', 'NNS'), ('.', '.')]

In [34]:
print(ne_chunk(pos_tags))

(S
  Artificial/JJ
  Intelligence/NNP
  is/VBZ
  an/DT
  emerging/VBG
  technology/NN
  ./.
  (PERSON Machine/NNP)
  learning/NN
  is/VBZ
  fascinating/VBG
  ./.
  (ORGANIZATION Computer/NNP Vision/NNP)
  handles/VBZ
  images/NNS
  ./.)

In [35]:
doc

I am Mohi Uddin Maruf. I am 25 years old. I live in Boalkhali.

In [36]:
for i in doc :
    print(f"{i.text} -> {i.ent_type_}")

I ->
am ->
Mohi -> PERSON
Uddin -> PERSON
Maruf -> PERSON
. ->
I ->
am ->
25 -> DATE
years -> DATE
old -> DATE
. ->
I ->
live ->
in ->
Boalkhali -> GPE
. ->

In [37]:
pos_tags = pos_tag(wtk)
print(pos_tags)

[('I', 'PRP'), ('am', 'VBP'), ('Mohi', 'NNP'), ('Uddin', 'NNP'), ('Maruf', 'NNP'), ('.', '.'), ('I', 'PRP'), ('am', 'VBP'), ('25', 'CD'), ('years', 'NNS'), ('old', 'JJ'), ('.', '.'), ('I', 'PRP'), ('live', 'VBP'), ('in', 'IN'), ('Boalkhali', 'NNP'), ('.', '.')]

In [38]:
chunks = ne_chunk(pos_tags)
print(chunks)

(S
  I/PRP
  am/VBP
  (PERSON Mohi/NNP Uddin/NNP Maruf/NNP)
  ./.
  I/PRP
  am/VBP
  25/CD
  years/NNS
  old/JJ
  ./.
  I/PRP
  live/VBP
  in/IN
  (GPE Boalkhali/NNP)
  ./.)

# Text Vectorizer

In [39]:
df = pd.read_excel('data.xlsx')
df

                          text  class
0      Hey, I love Bangladesh;      1
1  Good afternoon, I am happy!      1
2            I live in Germany      1
3        Nice to meet you man-      1
4            You won an iPhone      0

## Text Processing

In [40]:
from nltk.corpus import stopwords
en_stopwords = set(stopwords.words('english'))
print(en_stopwords)

{'to', "they'd", 'both', 'm', 'those', 'themselves', "haven't", "they've", 'too', 'over', 'some', 'these', 'we', 'now', 're', 'd', 'where', 'during', "don't", "he'll", 'itself', "they'll", "he's", 'myself', "wouldn't", 'and', 'from', 'hasn', 'very', 'mightn', "you've", 'most', 'him', 'haven', 'she', 'shan', 'did', 'will', 'a', "i'd", 'at', 'hadn', "hadn't", "it's", 'until', 'against', 'couldn', 'then', 'more', 'am', 'out', 'didn', 'wasn', 'off', 'aren', 'ma', "shouldn't", 'doesn', 'having', 'after', 'wouldn', 't', "weren't", 've', 'with', 'their', 'its', "aren't", "doesn't", 'down', 'had', 'own', 'not', 'our', 'them', "we've", "wasn't", 'here', 'her', 'between', 'for', 'but', 'yourselves', 'why', 'does', 'few', 'you', "we're", "you're", 'of', "mightn't", "hasn't", 'about', 'in', 'yourself', 'have', 'y', 'once', 'ourselves', 'so', "that'll", 'shouldn', "you'll", 'how', 'himself', 'has', 'no', 'each', "he'd", 'he', 'because', 'hers', 'are', 'such', 'up', 'what', 'just', "didn't", 'needn', "we'll", 'this', 'there', 'weren', "shan't", 'can', 'which', 'i', 'all', 'll', 'by', "mustn't", 'it', 'into', "she'll", 'who', 'my', 'do', 'nor', 'yours', 'is', 'below', "isn't", 'whom', 'than', 'don', 'while', 'been', 'won', 'theirs', 'were', 's', 'as', "we'd", 'any', 'same', 'under', 'the', "she's", "it'd", 'ain', 'again', "won't", 'be', 'being', 'o', "i'll", 'me', 'ours', 'if', 'an', 'only', "couldn't", "they're", "it'll", "you'd", "i've", 'above', 'before', 'doing', 'or', 'when', 'they', 'your', 'his', 'through', 'that', 'herself', 'should', "i'm", 'isn', "needn't", 'further', 'mustn', "she'd", 'other', 'on', 'was', "should've"}

In [41]:
ben_stopwords = set(stopwords.words('bengali'))
print(ben_stopwords)

{'ছিল', 'সে', 'কী', 'ওঁর', 'বিভিন্ন', 'অথচ', 'দেখতে', 'জানানো', 'প্রাথমিক', 'ফের', 'সামনে', 'সুতরাং', 'রকম', 'বিশেষ', 'করেছিলেন', 'পরে', 'কাজ', 'কাউকে', 'জন্যওজে', 'মধ্যেও', 'হইবে', 'চান', 'প্রভৃতি', 'রেখে', 'করিয়া', 'ছাড়াও', 'তখন', 'নিতে', 'তবে', 'এবার', 'কেউই', 'হলো', 'লক্ষ', 'জানা', 'তাঁরা', 'নেওয়ার', 'এটা', 'ফলে', 'তাহাতে', 'আরও', 'দিয়ে', 'এখন', 'নেই', 'বসে', 'স্বয়ং', 'হন', 'এঁরা', 'পর্যন্ত', 'হইয়া', 'দুটো', 'এমনি', 'সেটাও', 'যাওয়া', 'কয়েক', 'করাই', 'হওয়ায়', 'বরং', 'ওঁরা', 'থাকবেন', 'যত', 'মধ্যে', 'তাঁকে', 'প্রথম', 'হল', 'আমরা', 'শুরু', 'দিন', 'জনকে', 'সেটা', 'হৈলে', 'তাকে', 'অথবা', 'নিজের', 'সম্প্রতি', 'অর্থাত', 'জানিয়ে', 'দুই', 'কিছুই', 'অনেকে', 'আছে', 'এসে', 'ব্যবহার', 'পরেও', 'পেয়্র্', 'গিয়ে', 'হত', 'হয়তো', 'এর', 'যদিও', 'সঙ্গে', 'ছিলেন', 'জনের', 'আজ', 'বললেন', 'যাতে', 'এল', 'মতোই', 'তবু', 'একবার', 'সেটাই', 'বন', 'চায়', 'করবে', 'যে', 'করা', 'করতে', 'করিতে', 'উত্তর', 'যাঁরা', 'বলেন', 'এতটাই', 'তাদের', 'ধামার', 'বি', 'প্রতি', 'করেছেন', 'বলে', 'নাগাদ', 'নয়', 'প্রযন্ত', 'কোনও', 'পারেন', 'ছাড়া', 'গুলি', 'তুলে', 'কেন', 'ওর', 'কাজে', 'দ্বারা', 'যাকে', 'করছে', 'সেটি', 'করেন', 'এস', 'যায়', 'করলে', 'হচ্ছে', 'হয়নি', 'মধ্যভাগে', 'দিকে', 'বিনা', 'অনুযায়ী', 'ফিরে', 'বার', 'তো', 'অবধি', 'হলেই', 'সাধারণ', 'যা', 'পি', 'দেওয়ার', 'কমনে', 'নানা', 'র', 'সঙ্গেও', 'তারপর', 'একটি', 'হয়েছে', 'হবে', 'বেশি', 'তেমন', 'হবেন', 'গিয়ে', 'বলেছেন', 'ওদের', 'হয়', 'করলেন', 'এটি', 'সমস্ত', 'আপনি', 'দেখে', 'আমাদের', 'তার', 'কারও', 'থাকেন', 'প্রায়', 'যাঁর', 'বেশ', 'ওরা', 'কেউ', 'নিয়ে', 'এঁদের', 'করি', 'থাকবে', 'থাকায়', 'তাঁাহারা', 'অবশ্য', 'তুমি', 'দেওয়া', 'নেওয়া', 'সহ', 'দেখা', 'এমন', 'থেকেই', 'জন্য', 'খুব', 'ধরা', 'থেকেও', 'দেয়', 'যতটা', 'শুধু', 'বলতে', 'নয়', 'থাকে', 'কারণ', 'ইত্যাদি', 'অনেক', 'ওঁদের', 'গেল', 'সবার', 'বহু', 'ওখানে', 'নিজে', 'জ্নজন', 'না', 'হইতে', 'হওয়ার', 'ই', 'তাও', 'হয়েছিল', 'কত', 'কখনও', 'তিনি', 'হয়', 'আমাকে', 'গেলে', 'হয়েছেন', 'দু', 'থাকা', 'ইহা', 'আই', 'কয়েক', 'কিংবা', 'বলল', 'ব্যাপারে', 'কে', 'মাধ্যমে', 'করবেন', 'একই', 'জানিয়েছে', 'সেখান', 'দেওয়া', 'সেখানে', 'ঠিক', 'তারা', 'চালু', 'এ', 'হতেই', 'তিনঐ', 'অতএব', 'দিলেন', 'ক্ষেত্রে', 'চেয়ে', 'নেওয়া', 'এক্', 'যথেষ্ট', 'করছেন', 'দিতে', 'উপরে', 'আবার', 'আগে', 'একে', 'তাহলে', 'পরেই', 'নাই', 'করায়', 'তাহার', 'আমি', 'করিয়ে', 'দুটি', 'কিন্তু', 'অনেকেই', 'জন', 'থেকে', 'রয়েছে', 'জে', 'রাখা', 'নিয়ে', 'এবং', 'হওয়া', 'তোমার', 'মতো', 'আদ্যভাগে', 'এরা', 'ঐ', 'কোন', 'কি', 'পর', 'আপনার', 'গিয়েছে', 'জানতে', 'ওই', 'কিছু', 'গেছে', 'এদের', 'যেতে', 'যাওয়ার', 'যেমন', 'তাতে', 'আর', 'সি', 'করেই', 'আগামী', 'তাঁর', 'বাদে', 'যাওয়া', 'এখানে', 'ধরে', 'হলেও', 'এই', 'হয়ে', 'অন্তত', 'জানায়', 'বিষয়টি', 'তাই', 'দেন', 'যাবে', 'হতে', 'মধ্যেই', 'কয়েকটি', 'এমনকী', 'যাদের', 'বলা', 'তারৈ', 'ভাবেই', 'বা', 'আমার', 'উচিত', 'কোটি', 'হোক', 'এব', 'করার', 'ও', 'ওকে', 'উনি', 'নিজেদের', 'পক্ষে', 'যাচ্ছে', 'পারি', 'সহিত', 'ভাবে', 'হয়েই', 'চার', 'যার', 'এখানেই', 'যিনি', 'করে', 'তাহা', 'নিজেই', 'প্রায়', 'পাওয়া', 'দিয়েছে', 'এত', 'কাছে', 'তথা', 'দিয়েছেন', 'মোটেই', 'তত', 'করেছে', 'এতে', 'মনে', 'আগেই', 'মোট', 'গোটা', 'সেই', 'যদি', 'টি', 'বদলে', 'হলে', 'অন্য', 'যেন', 'তাঁদের', 'স্পষ্ট', 'এখনও', 'উপর', 'কেখা', 'যারা', 'চলে', 'যখন', 'নতুন', 'হিসাবে', 'বক্তব্য', 'তিনিও', 'যেখানে', 'মাত্র', 'হাজার', 'কবে', 'পারে', 'পেয়ে', 'সব', 'কোনো', 'কাছ', 'এটাই', 'যান', 'পাচ', 'চেষ্টা', 'তা', 'নাকি'}

In [42]:
import string
punc = string.punctuation
punc

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [43]:
len(punc)

32

In [44]:
def preprocess_text(text) :
    remove_punc = [char for char in text if char not in punc]
    clean_words = ''.join(remove_punc)
    split_words = clean_words.split()
    text = [word for word in split_words if word.lower() not in en_stopwords]
    return text

In [45]:
df

                          text  class
0      Hey, I love Bangladesh;      1
1  Good afternoon, I am happy!      1
2            I live in Germany      1
3        Nice to meet you man-      1
4            You won an iPhone      0

In [46]:
df.columns

Index(['text', 'class'], dtype='object')

In [47]:
tmp = df['class']
df.drop(columns = ['class'], inplace = True)
df['cleaned_text'] = df.text.apply(preprocess_text)
df['class'] = tmp

In [48]:
df

                          text              cleaned_text  class
0      Hey, I love Bangladesh;   [Hey, love, Bangladesh]      1
1  Good afternoon, I am happy!  [Good, afternoon, happy]      1
2            I live in Germany           [live, Germany]      1
3        Nice to meet you man-         [Nice, meet, man]      1
4            You won an iPhone                  [iPhone]      0

In [49]:
lemmatizer = WordNetLemmatizer()
lemmatizer

In [50]:
def lemmatize_text(text_list):
    clean_text = []
    for word in text_list :
        clean_text.append(lemmatizer.lemmatize(word))

    return ' '.join(clean_text)


tmp = df['class']
df.drop(columns = ['class'], inplace = True)
df['lemmatize_text'] = df.cleaned_text.apply(lemmatize_text)
df['class'] = tmp
df

,text,cleaned_text,lemmatize_text,class
0,"Hey, I love Bangladesh;","[Hey, love, Bangladesh]",Hey love Bangladesh,1
1,"Good afternoon, I am happy!","[Good, afternoon, happy]",Good afternoon happy,1
2,I live in Germany,"[live, Germany]",live Germany,1
3,Nice to meet you man-,"[Nice, meet, man]",Nice meet man,1
4,You won an iPhone,[iPhone],iPhone,0

In [51]:
df1 = df.copy()
df2 = df.copy()
df3 = df.copy()
df4 = df.copy()
df5 = df.copy()

# CountVectorizer

In [52]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [53]:
cv = CountVectorizer()
cv

CountVectorizer()

In [54]:
cv_x = cv.fit_transform(df['lemmatize_text'])
cv_x

<5x12 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [55]:
cv_x.toarray()

array([[0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]], dtype=int64)

In [56]:
cv_df = pd.DataFrame(cv_x.toarray())
cv_df

   0   1   2   3   4   5   6   7   8   9   10  11
0   0   1   0   0   0   1   0   0   1   0   0   0
1   1   0   0   1   1   0   0   0   0   0   0   0
2   0   0   1   0   0   0   0   1   0   0   0   0
3   0   0   0   0   0   0   0   0   0   1   1   1
4   0   0   0   0   0   0   1   0   0   0   0   0

In [57]:
cv.get_feature_names_out()

array(['afternoon', 'bangladesh', 'germany', 'good', 'happy', 'hey',
       'iphone', 'live', 'love', 'man', 'meet', 'nice'], dtype=object)

In [58]:
cv_df = pd.DataFrame(cv_x.toarray(), index = df['lemmatize_text'], columns = cv.get_feature_names_out())

In [59]:
cv_df

,afternoon,bangladesh,germany,good,happy,hey,iphone,live,love,man,meet,nice
lemmatize_text,,,,,,,,,,,,
Hey love Bangladesh,0,1,0,0,0,1,0,0,1,0,0,0
Good afternoon happy,1,0,0,1,1,0,0,0,0,0,0,0
live Germany,0,0,1,0,0,0,0,1,0,0,0,0
Nice meet man,0,0,0,0,0,0,0,0,0,1,1,1
iPhone,0,0,0,0,0,0,1,0,0,0,0,0

# TfidfVectorizer

In [60]:
tfidf = TfidfVectorizer()
tfidf

TfidfVectorizer()

In [61]:
tfidf_x = tfidf.fit_transform(df1['lemmatize_text'])
tfidf_x

<5x12 sparse matrix of type '<class 'numpy.float64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [62]:
tfidf_x.toarray()

array([[0.        , 0.57735027, 0.        , 0.        , 0.        ,
        0.57735027, 0.        , 0.        , 0.57735027, 0.        ,
        0.        , 0.        ],
       [0.57735027, 0.        , 0.        , 0.57735027, 0.57735027,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.70710678, 0.        , 0.        ,
        0.        , 0.        , 0.70710678, 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.57735027,
        0.57735027, 0.57735027],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

In [63]:
tfidf_df = pd.DataFrame(tfidf_x.toarray(), index = df1['lemmatize_text'], columns = tfidf.get_feature_names_out())
tfidf_df

,afternoon,bangladesh,germany,good,happy,hey,iphone,live,love,man,meet,nice
lemmatize_text,,,,,,,,,,,,
Hey love Bangladesh,0.00000,0.57735,0.000000,0.00000,0.00000,0.57735,0.0,0.000000,0.57735,0.00000,0.00000,0.00000
Good afternoon happy,0.57735,0.00000,0.000000,0.57735,0.57735,0.00000,0.0,0.000000,0.00000,0.00000,0.00000,0.00000
live Germany,0.00000,0.00000,0.707107,0.00000,0.00000,0.00000,0.0,0.707107,0.00000,0.00000,0.00000,0.00000
Nice meet man,0.00000,0.00000,0.000000,0.00000,0.00000,0.00000,0.0,0.000000,0.00000,0.57735,0.57735,0.57735
iPhone,0.00000,0.00000,0.000000,0.00000,0.00000,0.00000,1.0,0.000000,0.00000,0.00000,0.00000,0.00000

# Word2Vec

In [64]:
from gensim.models import Word2Vec, KeyedVectors
import nltk

In [65]:
df.columns

Index(['text', 'cleaned_text', 'lemmatize_text', 'class'], dtype='object')

In [66]:
df

,text,cleaned_text,lemmatize_text,class
0,"Hey, I love Bangladesh;","[Hey, love, Bangladesh]",Hey love Bangladesh,1
1,"Good afternoon, I am happy!","[Good, afternoon, happy]",Good afternoon happy,1
2,I live in Germany,"[live, Germany]",live Germany,1
3,Nice to meet you man-,"[Nice, meet, man]",Nice meet man,1
4,You won an iPhone,[iPhone],iPhone,0

In [67]:
text_vector = []
for sen in df['lemmatize_text'] :
    text_vector.append(list(nltk.word_tokenize(sen)))
    
text_vector

[['Hey', 'love', 'Bangladesh'],
 ['Good', 'afternoon', 'happy'],
 ['live', 'Germany'],
 ['Nice', 'meet', 'man'],
 ['iPhone']]

In [68]:
model = Word2Vec(text_vector, min_count = 1)
model

In [69]:
model.wv.most_similar('iPhone')

[('Bangladesh', 0.21617142856121063),
 ('afternoon', 0.09291722625494003),
 ('Hey', 0.07963486760854721),
 ('love', 0.06285078823566437),
 ('Good', 0.0270574688911438),
 ('happy', 0.016134677454829216),
 ('man', -0.01083916611969471),
 ('Germany', -0.027750369161367416),
 ('meet', -0.05234673246741295),
 ('live', -0.059876296669244766)]

In [70]:
model_df = pd.DataFrame(model.wv.vectors, index = model.wv.index_to_key, columns = [i for i in range(model.wv.vectors.shape[1])])

In [71]:
model_df

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
iPhone,-0.000536,0.000236,0.005103,0.009009,-0.009303,-0.007117,0.006459,0.008973,-0.005015,-0.003763,...,0.001631,0.000190,0.003474,0.000218,0.009619,0.005061,-0.008917,-0.007042,0.000901,0.006393
man,-0.008620,0.003666,0.005190,0.005742,0.007467,-0.006168,0.001106,0.006047,-0.002840,-0.006174,...,0.001088,-0.001576,0.002197,-0.007882,-0.002717,0.002663,0.005347,-0.002392,-0.009510,0.004506
meet,0.000095,0.003077,-0.006813,-0.001375,0.007669,0.007346,-0.003673,0.002643,-0.008317,0.006205,...,-0.004509,0.005702,0.009180,-0.004100,0.007965,0.005375,0.005879,0.000513,0.008213,-0.007019
Nice,-0.008243,0.009299,-0.000198,-0.001967,0.004604,-0.004095,0.002743,0.006940,0.006065,-0.007511,...,-0.007426,-0.001064,-0.000795,-0.002563,0.009683,-0.000459,0.005874,-0.007448,-0.002506,-0.005550
Germany,-0.007139,0.001241,-0.007177,-0.002245,0.003719,0.005833,0.001198,0.002103,-0.004110,0.007225,...,0.003137,-0.004713,0.005281,-0.004233,0.002642,-0.008046,0.006210,0.004819,0.000787,0.003013
live,-0.008727,0.002130,-0.000874,-0.009319,-0.009428,-0.001411,0.004432,0.003704,-0.006499,-0.006873,...,0.009071,0.008938,-0.008208,-0.003012,0.009887,0.005104,-0.001588,-0.008692,0.002962,-0.006676
happy,0.008132,-0.004457,-0.001068,0.001006,-0.000191,0.001148,0.006114,-0.000020,-0.003246,-0.001511,...,-0.002701,0.000444,-0.003537,-0.000419,-0.000709,0.000823,0.008195,-0.005737,-0.001660,0.005572
afternoon,0.008168,-0.004443,0.008985,0.008254,-0.004435,0.000303,0.004274,-0.003926,-0.005560,-0.006512,...,0.002058,-0.004004,-0.008241,0.006278,-0.001949,-0.000666,-0.001771,-0.004536,0.004062,-0.004270
Good,-0.009579,0.008943,0.004165,0.009235,0.006644,0.002925,0.009804,-0.004425,-0.006803,0.004227,...,-0.005085,0.001131,0.002883,-0.001536,0.009932,0.008350,0.002416,0.007118,0.005891,-0.005581
Bangladesh,-0.005156,-0.006668,-0.007777,0.008311,-0.001982,-0.006855,-0.004154,0.005144,-0.002869,-0.003750,...,-0.008977,0.008592,0.004047,0.007470,0.009746,-0.007290,-0.009040,0.005836,0.009391,0.003507
love,0.007089,-0.001568,0.007947,-0.009489,-0.008029,-0.006640,-0.004003,0.004989,-0.003814,-0.008320,...,0.007512,0.001498,-0.001265,0.005768,-0.005640,0.000039,0.009457,-0.005481,0.003814,-0.008113
Hey,0.009770,0.008165,0.001281,0.005098,0.001408,-0.006455,-0.001428,0.006449,-0.004617,-0.003993,...,0.004774,-0.003262,-0.009268,0.003787,0.007161,-0.005633,-0.007865,-0.002973,-0.004932,-0.002315